import { StaffExperience } from "./staff-experience";
import { Address } from "../../shared/address/address";

export class Staff {
      salutation: string | undefined;
      dob: Date | undefined;
      religionId: string | undefined;
      motherTonge: string | undefined;
      firstName: string | undefined;
      bloodGroup: string | undefined;
      gender: string | undefined;
      emailId: string | undefined;
      languages: string | undefined;
      middleName: string | undefined;
      maritalStatus: string | undefined;
      nationality: string | undefined;
      personalEmail: string | undefined;
      lastName: string | undefined;
      weedingDate: string | undefined;
      mobileNumber: string | undefined;
      aadharNumber: string | undefined;
      fatherName: string | undefined;
      motherName: string | undefined;
      spouseName: string | undefined;
      fatherOccupation: string | undefined;
      motherOccupation: string | undefined;
      souseOccupation: string | undefined;
      fatherMobileNumber: string | undefined;
      motherMobileNumber: string | undefined;
      spouseMobileNumber: string | undefined;
      teacherId : string | undefined;
      employeeId : string | undefined;
      educationId : string | undefined;
      officialEmailId : string | undefined;
      esiNumber : string | undefined;
      staffId : string | undefined;
      employeementstatusId : string | undefined;
      reportingTo : string | undefined;
      epfNumber : string | undefined;
      departmentId : string | undefined;
      joiningDate : string | undefined;
      activeId : string | undefined;
      uanNumber : string | undefined;
      designationId : string | undefined;
      roleId : string | undefined;
      bankName : string | undefined;
      bankAccountNumber : string | undefined;
      panNumber : string | undefined;
      branchNumber : string | undefined;
      bankIfscCode : string | undefined;
      from : Date | undefined;
        to: Date | undefined;
        responsiblity: Date | undefined;
     // staffExperience : StaffExperience[] | undefined;
      addresses : Address[] | undefined;
}
